### ISSUE TITLE
while download the pretrained weights, the url can't fetch.  May I download the weights from google drive or other places. or use my own trained weights?

### ISSUE THREAD

**Issue by simzhangbest** [lassoan/SlicerTotalSegmentator#13]
requests.exceptions.SSLError: HTTPSConnectionPool(host='zenodo.org', port=443): Max retries exceeded with url: /record/6802342/files/Task251_TotalSegmentator_part1_organs_1139subj.zip?download=1 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

**Comment by lassoan** [comment]
Most likely you are behind a proxy server or corporate firewall. Let's continue the discussion here: https://discourse.slicer.org/t/ssl-error-when-lung-ct-segmenter-is-trying-to-instal-light-the-torch/28774

**Comment by xiaoli26** [comment]
The solution is download all the weight file from the zenodo manually and paste the zip files to the folder "C:\Users\XXXX\.totalsegmentator\nnunet\results\nnUNet\3d_fullres"
