### ISSUE TITLE
Exception raised when CUDA not available for a CUDA-versioned torch

### ISSUE THREAD

**Issue by subelf** [lassoan/SlicerTotalSegmentator#14]
I modified TotalSegmentator.py going through some more CUDA availability test
Also this makes it possible to disable CUDA temporarily by setting up environment variable 'CUDA_VISIBLE_DEVICES'

And here is the patch:

```--- TotalSegmentator.py	2023-03-05 12:45:50.536210700 +0800
+++ TotalSegmentator.py	2023-03-05 13:31:58.226645800 +0800
@@ -685,10 +685,14 @@
 
         # Recommend the user to switch to fast mode if no GPU or not enough memory is available
         import torch
-        if not fast and not torch.has_cuda:
+
+        cuda = torch.cuda if torch.has_cuda and torch.cuda.is_available() else None
+
+        if not fast and not cuda:
             if slicer.util.confirmYesNoDisplay("No GPU is detected. Enable 'fast' mode to get low-resolution result in about 1 minute (instead of full-resolution in 1 hour)?"):
                 fast = True
-        if not fast and torch.has_cuda and torch.cuda.get_device_properties(0).total_memory < 7e9:
+
+        if not fast and cuda and cuda.get_device_properties(cuda.current_device()).total_memory < 7e9:
             if slicer.util.confirmYesNoDisplay("You have less than 7 GB of GPU memory available. Enable 'fast' mode to ensure segmentation can be completed successfully?"):
                 fast = True
```

**Comment by subelf** [comment]
Besides, maybe it'll be nice if we provide a choice for user to cancel the boring process that either get a low-resolution result or take a long time.

**Comment by lassoan** [comment]
Would you mind submitting a pull request? That would ensure that your contribution is acknowledged and saves a few minutes for me.

Please also rename `cuda` to something like `isCudaAvailable`.

Since the inference runs in a separate process, it is easy to abort it. Please submit a feature request (and preferably a pull request with a proposed implementation). Thank you!

**Comment by subelf** [comment]
> Would you mind submitting a pull request? That would ensure that your contribution is acknowledged and saves a few minutes for me.

Well I'll start that workflow right away.
C u later.

**Comment by subelf** [comment]
Referred to a PR:
https://github.com/lassoan/SlicerTotalSegmentator/pull/15
