### ISSUE TITLE
Pytorch 2.0 cu18 win - very slow

### ISSUE THREAD

**Issue by ayalalazaro** [lassoan/SlicerTotalSegmentator#21]
Updating from torch1.13.1 cu17 to torch 2.0 cu18 increases computation time more than 2x. From 80 s to 180 s when segmentating CTA abdomen (panoramix) in a GTX1660 super in a windows system.

Not sure if it is due to pytorch or cuda version.

**Comment by lassoan** [comment]
Torch 1.x to 2.x is a huge change, so I would not be surprised to see performance regressions with a model that was developed for Torch 1.x.

That said, I cannot reproduce the slower performance wit Torch 2.x on Windows 10 with NVIDIA RTX 3060 GPU. Segmentation time using Torch 1.13.1+cu117 vs Torch 2.0.0+cu118:
- fast: 22.44s vs 22.76s
- full resolution: 69.48s vs 69.08s

NVIDIA GeForce GTX 1660 SUPER was released about 4 years ago, and so maybe the drivers or newer techniques that Torch 2.x uses are not optimized for it. If you consistently get better computation time with Torch 1.x then you can force TotalSegmentator to install Torch 1.x by changing [this line](https://github.com/fepegar/SlicerPyTorch/blob/master/PyTorchUtils/PyTorchUtils.py#L199):

From:

```python
args = ["install","torch"]
```

To:

```python
args = ["install","torch<2"]
```

**Comment by ayalalazaro** [comment]
I have the same behaviour with a GTX 1070 win10, it is even older than the 1660 super. Let s blame pytorch major version change.
Thanks for your help.
