### ISSUE TITLE
Wrong action for "fast" button

### ISSUE THREAD

**Issue by x1y9** [lassoan/SlicerTotalSegmentator#24]
When I run this extension, I get a dialog box to select 'fast' or 'full' mode, It's ok, but after I select 'fast', the extension use 'full'.

I think it's a bug of 
```
mbox.addButton("Fast (~2 minutes)", qt.QMessageBox.AcceptRole)
mbox.addButton("Full-resolution (~50 minutes)", qt.QMessageBox.RejectRole)
```

but, I changed it to :
```
mbox.addButton("Fast (~2 minutes)", qt.QMessageBox.RejectRole)
mbox.addButton("Full-resolution (~50 minutes)", qt.QMessageBox.AcceptRole)
```
still wrong, then I changed it to:

```
mbox.addButton("Full-resolution (~50 minutes)", qt.QMessageBox.RejectRole)
mbox.addButton("Fast (~2 minutes)", qt.QMessageBox.AcceptRole)
```

Now it's ok, but I am confused, I am not familiar with qt, why the sequence of addButton is relevant?

**Comment by lassoan** [comment]
Fast mode is not supported by all segmentation tasks. The module should not recommend to use fast mode in these cases.

**Comment by x1y9** [comment]
What I mean is that the fast and full buttons are reversed, when I select the fast button, the full operation is executed and when I select the full button, the fast operation is executed.
