### ISSUE TITLE
List of tasks do not account for additional tasks available under licensing

### ISSUE THREAD

**Issue by RafaelPalomar** [lassoan/SlicerTotalSegmentator#26]
TotalSegmentator has some organs available only under licensing. Enabling this requires additional tasks not listed in SlicerTotalSegmentator. It would be nice if SlicerTotalSegmentator could detect what's available in TotalSegmentator (including organs under license).

**Comment by lassoan** [comment]
All tasks are available now and there is GUI to specify license key.

**Comment by callmebigbig** [comment]
Hi I'm using slicer 5.6.2 and cannot find where to set the license key. Could you please help me?
