### ISSUE TITLE
Total segmentator not running after restart

### ISSUE THREAD

**Issue by law0890** [lassoan/SlicerTotalSegmentator#27]
I am new to segmentation software. I have read that all you have to do is restart the 3D slicer; however, nothing is working still. I am getting the same error message each time.

**Comment by lassoan** [comment]
To investigate, we would need to get the full text of all error messages that you see in the textbox in the module and in the application log.

**Comment by haozhi1817** [comment]
> I am new to segmentation software. I have read that all you have to do is restart the 3D slicer; however, nothing is working still. I am getting the same error message each time.

If you can not install 'light_the_torch' you can download whl package, and use **PythonSlicer.exe install xxx.whl**

**Comment by lassoan** [comment]
Please try the clean install of the latest Slicer-5.4 release (provides TotalSegmentator v1) or the latest Slicer-5.5 release (provides TotalSegmentator v2). Both should work without any restart.
