### ISSUE TITLE
Distance between slices

### ISSUE THREAD

**Issue by law0890** [lassoan/SlicerTotalSegmentator#29]
Hi,

I am currently segmenting something from a screenshot. Therefore, it is a 2D image. I am wanting to make it into a 2D surface mesh. I was told since 3D slicer will only export as 3D .stl files, to duplicate the segment and put distance between them. As a beginner, I really have no idea how to do that. Could you help?

**Comment by lassoan** [comment]
If you need to segment a single image slice (not from a 3D image) then you will not be able to use TotalSegmentator model for that. There are many other segmentation tools that may be usable, depending on what exactly you want to achieve. You can ask for more details on the Slicer forum: https://discourse.slicer.org

**Comment by lassoan** [comment]
Follow up here: https://discourse.slicer.org/t/distance-between-slices/30730
