### ISSUE TITLE
TotalSegmentator replaces Slicer's SimpleITK

### ISSUE THREAD

**Issue by lassoan** [lassoan/SlicerTotalSegmentator#4]
TotalSegmentator [specifies a concrete SimpleITK version](https://github.com/wasserth/TotalSegmentator/issues/32), which makes pip replace Slicer's SimpleITK, causing all kinds of troubles. (continued from #1)

**Comment by lassoan** [comment]
I've implemented a combined workaround for the SimpleITK issue (modify TotalSegmentator package METADATA file + install dependencies manually). With these changes, everything seems to work robustly.

@rbumm please test (using a clean Slicer install)

**Comment by rbumm** [comment]
I´ve tested a full installation run in a clean Slicer 5.2.1 install: 

- Totalsegmentator installs and runs without error
- Then installed SegmentEditorExtraEffetcs, WrapSolidify
- Included the local SlicerLungCtAnalyzer module path (development branch)
- Restarted
- Ran Lung CT Segmenter in "lungmask" AI mode without error
- Ran Lung CT Segmenter in "TotalSegmentator" AI mode without error

Perfect!

**Comment by lassoan** [comment]
Perfect, thank you for the thorough testing, I'm closing this issue then.
