### ISSUE TITLE
Missing items from TotalSegmentator v2 mapping

### ISSUE THREAD

**Issue by lassoan** [lassoan/SlicerTotalSegmentator#42]
These labels are missing from the mapping csv file:
- vertebrae_S1
- thyroid_gland

**Comment by lassoan** [comment]
@fedorov The TotalSegmentator v2 mapping is almost complete, just two labels are missed (see above). Could you add their mapping to the .csv file? Thank you! If it is done then it could make sense to submit the .csv to the [TotalSegmentator repository](https://github.com/wasserth/TotalSegmentator), too.

**Comment by fedorov** [comment]
> If it is done then it could make sense to submit the .csv to the [TotalSegmentator repository](https://github.com/wasserth/TotalSegmentator), too.

I agree. I will do it once it is updated here first.

**Comment by fedorov** [comment]
@lassoan can you please let me know what are the label numbers for those 2 missing labels, and where they are located in TotalSegmentator repo? I tried and failed in looking for those.

**Comment by lassoan** [comment]
I don't think there are fixed label values (each task uses different label values). You can find find S1 here: https://github.com/wasserth/TotalSegmentator/blob/cad2230bc2756c555b13afa5282019d1c87b7a5a/totalsegmentator/map_to_binary.py#L138 the other one is in the same file.

We can probably remove the label numbers from the .csv but you can ask Jakob to confirm.
