### ISSUE TITLE
Old UI present when used with 3D Slicer 5.4.0

### ISSUE THREAD

**Issue by rbumm** [lassoan/SlicerTotalSegmentator#46]
3D Slicer 5.4.0 installed and updated Totalsegmentator extension.  

Import license expects a zip license  file, but currently, we circulate written licenses which can not be used (entered) with 5.4.0 

![image](https://github.com/lassoan/SlicerTotalSegmentator/assets/18140094/a49f6533-55b2-48f6-8072-603a8ceb690c)

In addition, we removed the "use latest development version" checkbox

So we have currently two UI´s ?

**Comment by lassoan** [comment]
I kept Slicer-5.4 on TotalSegmentator v1, to allow people access to both TS v1 and v2 versions in still supported Slicer versions. Differences Python requirements of TS v1 vs v2; and differences in bundled Python packages versions in Slicer 5.4 vs 5.5 made it impractical to support all the different combinations. Therefore, I kept TS 1 for Slicer-5.4 and switched to TS2 in Slicer-5.5 (see s4ext files of [Slicer-5.4](https://github.com/Slicer/ExtensionsIndex/blob/beccf5ff024bcf595ed05cdde6e79dc19f61fe7d/TotalSegmentator.s4ext#L10) and [Slicer-5.5](https://github.com/Slicer/ExtensionsIndex/blob/c87cbf488009a2ba23710c9553b0dd02872795a1/TotalSegmentator.s4ext#L10)).

Slicer-5.4 will get a 5.4.1 patch release within a couple of weeks that is based on a recent Slicer-5.5 version. Then Slicer-5.4 and Slicer-5.5 will use the same TotalSegmentator extension version again.

**Comment by rbumm** [comment]
It is just that when a user tries to enter a license, now it will open a dialog box expecting a zip file. 
But the extension code needs a license code from a password text box to register the additional segentation effect. So in short the current circulated version will not work regarding registration. Could you maybe show an error message when the user tries to attempt the registration with "work in progress"  as long as we work with the 5.4.0 UI ?

**Comment by lassoan** [comment]
Extensions are only updated for latest Slicer Stable Release and latest Slicer Preview Release, so we cannot update Slicer-5.4 extensions. Users need to switch to latest Slicer version to get latest extension version.
