### ISSUE TITLE
Feature Request: Segment all volumes in a sequence

### ISSUE THREAD

**Issue by henrykrumb** [lassoan/SlicerTotalSegmentator#53]
I tried segmenting the CT cardio sequence from "Download example data". The segmentation itself worked fine and didn't produce any errors, however the segmentation mask remains the same for all frames of the sequence.

I followed the instructions in this thread:
https://discourse.slicer.org/t/segmentation-of-multi-volume-sequence/5187/2
and it did work – I had to enable the segmentation mask to be recorded in the sequence as well, after running TotalSegmentator once. However, I had to manually run TotalSegmentator on each frame individually. This could be cumbersome on longer sequences.

I would thus suggest to implement the following:

1. If a user runs TotalSegmentator on an image tracked by a sequence, they will be asked if they want to auto-segment the full sequence. Similar to the dialog I see when I run TotalSegmentator on CPU without enabling "fast" mode.
2. If the user confirmed, add the resulting segmentation node to be tracked in a new sequence.
3. Run TotalSegmentator on each frame of the volume sequence. And give the user some feedback about its progress.

**Comment by lassoan** [comment]
This is implemented now.
