### ISSUE TITLE
Howto import the segmented `.nii` file into the scene of 'slicer' through code?

### ISSUE THREAD

**Issue by jumbojing** [lassoan/SlicerTotalSegmentator#57]
Howto import the segmented `.nii` file into the scene of 'slicer' through code?

Or add a checked box for 'import labelmapvolume'?

**Comment by lassoan** [comment]
See https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#load-a-3d-image-or-model-file-as-segmentation

This issue tracker is for tracking problems in the extension. Please use the Slicer forum (https://discourse.slicer.org) to ask questions.

**Comment by jumbojing** [comment]
@lassoan Sorry, I didn't make it clear What I mean is that in the 'totalsegmentator' plugin howto import the `totalsegmented`  `.nii file` into the scene of 'slicer' through code or add a checked box for 'import(or delete) labelmapvolume' to this extension?
I want to a multilabel 'totalsegment' labelMapVolume, howto get it in the `slicerTotalSegmentator` extension with python code?

**Comment by lassoan** [comment]
I  still don't understand your question. TotalSegmentator extension automatically loads the segmentation results. You can convert the segmentation to labelmap - there are Python examples for all these kinds of things in the script repository, just search on the page that I linked above. If you still need help with this, please post it to the Slicer forum, the issue tracker here is for tracking issues, not for questions&answers. Thank you.
