### ISSUE TITLE
Feature request: a checked box 'import labelMapVolume'

### ISSUE THREAD

**Issue by jumbojing** [lassoan/SlicerTotalSegmentator#58]
Feature request: a checked box 'import labelMapVolume' in order to import the segmented .nii file with labels of [TotalSegmentator](https://github.com/wasserth/TotalSegmentator) to the `slicer` scene.

**Comment by lassoan** [comment]
TotalSegmentator already automatically loads the segmentation results into the scene. If you have questions about how to use this extension then please post it to the [Slicer forum](https://discourse.slicer.org).
