### ISSUE TITLE
nn-U-Net multiprocessing error with fix

### ISSUE THREAD

**Issue by rbumm** [lassoan/SlicerTotalSegmentator#7]
@lassoan are you aware of the nnU-Net multiprocessing error that occurs on Windows? It did not let me run TotalSegmentator initially. There is still no response to the PR with the fix I made. 

MIC-DKFZ/nnUNet#1155

Are you solving this locally during installation or do I oversee a fix that they made?

**Comment by lassoan** [comment]
I don't have any errors when using TotalSegmentator extension on Windows in Slicer's Python environment. Everything works well both on a desktop with an NVIDIA GPU and cuda enabled; and on a laptop without a discrete GPU.

What Python distribution you have problem with? Slicer's Python, https://www.python.org/, or anaconda?

**Comment by rbumm** [comment]
Just checked the Python libs of my local Slicer installation: 

In 

C:\\Users\\rudol\\AppData\\Local\\NA-MIC\\Slicer 5.2.1\\lib\\Python\\Lib\\site-packages\\nnunet\\inference\\predict.py

```
if 'win' in sys.platform:
    #fix for windows platform
    import pathos
    Process = pathos.helpers.mp.Process
    Queue = pathos.helpers.mp.Queue
else:
    from multiprocessing import Process, Queue
```

is now included, which was the fix I suggested. Can you confirm the same on your system?

**Comment by lassoan** [comment]
TotalSegmentator is using this slightly modified version of nnunet, which includes your fix: https://github.com/wasserth/nnUNet_cust/commits/working_2022_03_18

This bug should be really fixed upstream in the official nnUNet repository, so I've [pinged the maintainers](https://github.com/MIC-DKFZ/nnUNet/pull/1155#issuecomment-1345366807).

**Comment by rbumm** [comment]
Great, thanks.
