### ISSUE TITLE
Feature Request:  Advanced Settings

### ISSUE THREAD

**Issue by bpataybac** [lassoan/SlicerTotalSegmentator#8]
Hi,  Thanks for adding this Extension to 3D Slicer.  

Under Outputs could you create GUI for these two options?
  
--statistics: This will generate a file statistics.json with volume (in mm³) and mean intensity of each class.
--radiomics: This will generate a file statistics_radiomics.json with radiomics features of each class. You have to install pyradiomics to use this (pip install pyradiomics).

As per https://github.com/wasserth/TotalSegmentator.

Thanks for all of your insights over the years.  Brad

**Comment by lassoan** [comment]
Thanks for the suggestions. These features of TotalSegmentator are not exposed in Slicer because much improved versions of these features are already available:
- You can get more detailed statistics in Segment Statistics module.
- You can run radiomics using SlicerRadiomics extension.
